// Package cellslicer partitions a sliced model into per-slab cells:
// small 2D polygons that tile each slab's footprint. Cells are the
// unit of color sampling and dithering in the cellslicer pipeline;
// the original mesh is later Boolean-cut along each cell's prism so
// triangle fragments inherit the enclosing cell's color.
//
// The package owns slab partition and cell polygon generation. It
// reuses internal/minislicer for the Z-plane slicing primitive
// (SliceMesh, Loop, Point2). Once the minislicer pipeline is
// retired, those primitives will be inlined here.
package cellslicer

import "github.com/rtwfroody/ditherforge/internal/minislicer"

// CellKind distinguishes ring cells (along the slab's boundary) from
// hex cells (filling the slab's interior).
type CellKind uint8

const (
	// KindRing is a cell generated by walking the outer footprint at
	// cellSize arc spacing; its outer edge is a chord of the
	// footprint boundary and it extends inward.
	KindRing CellKind = iota
	// KindHex is a (regular or boundary-clipped) hexagon tessellating
	// the inward-offset footprint.
	KindHex
)

// Cell is a single XY polygon at a slab. The polygon is the result
// of Clipper-clipping a raw ring trapezoid or hex against the slab's
// footprint, so it lies entirely inside the footprint and its edges
// may not be straight (each clipped polygon can have more vertices
// than the original ring/hex).
type Cell struct {
	// Outer is the cell's outer boundary, CCW, no closing duplicate.
	Outer []minislicer.Point2
	Kind  CellKind
}

// Slab is one Z-stratum of the partitioned model. ZBot < ZTop. Cells
// tile (most of) the slab's XY footprint; rasterization-based small-
// cell merge happens downstream of this package.
type Slab struct {
	// Index is the slab's index within the model's slab list, 0-based.
	Index int
	// ZBot, ZTop bound the slab in Z (mm).
	ZBot, ZTop float32
	// BotLayer / TopLayer are the slicer's per-Z contour layers at
	// ZBot and ZTop. Retained so downstream code can look up source
	// triangles for color sampling without re-slicing.
	BotLayer *minislicer.Layer
	TopLayer *minislicer.Layer
	// Footprint is the Clipper union of bot + top loops. Cells lie
	// inside it.
	Footprint *Footprint
	// Cells is the slab's cell list. Order is ring-cells first
	// (loop-by-loop), then hex cells.
	Cells []Cell
}
