// Package cellslicer partitions a sliced model into per-slab cells:
// small 2D polygons that tile each slab's footprint. Cells are the
// unit of color sampling and dithering in the cellslicer pipeline;
// the original mesh is later intersected (via Manifold's 3D boolean
// in clip_manifold.go) against each cell's prism so triangle fragments
// inherit the enclosing cell's color.
//
// The package owns Z-plane slicing (SliceMesh + Loop + Point2), slab
// partition, cell polygon generation, adjacency, sampling, and the
// per-cell Manifold Clip stage.
package cellslicer

// CellKind distinguishes ring cells (along the slab's boundary) from
// hex cells (filling the slab's interior).
type CellKind uint8

const (
	// KindRing is a cell generated by walking the outer footprint at
	// cellSize arc spacing; its outer edge is a chord of the
	// footprint boundary and it extends inward.
	KindRing CellKind = iota
	// KindHex is a (regular or boundary-clipped) hexagon tessellating
	// the inward-offset footprint.
	KindHex
)

// Cell is a single XY polygon at a slab. The polygon is the result
// of Clipper-clipping a raw ring trapezoid or hex against the slab's
// footprint, so it lies entirely inside the footprint and its edges
// may not be straight (each clipped polygon can have more vertices
// than the original ring/hex).
type Cell struct {
	// Outer is the cell's outer boundary, CCW, no closing duplicate.
	Outer []Point2
	Kind  CellKind
	// Pixels is a coarse size estimate: the cell's polygon area in
	// units of (cellSize/4)², matching what the old raster path
	// counted at pxSize = cellSize/4. Diagnostic only (the pipeline's
	// partition size histogram). Zero for cells from paths that don't
	// set it (e.g. the PartitionSlab path used by slice.go).
	Pixels int
	// OuterEdgeOpen, when non-nil, has length len(Outer) and marks
	// whether each cell-Outer edge lies on the slab partition's outer
	// boundary — i.e. no other cell in the slab owns its reverse
	// half-edge AND the half-space immediately outside the edge falls
	// outside the slab footprint.
	//
	// ClipMeshToCellsManifold treats "outer" edges as open: it nudges
	// them outward by a few µm (OpenEdgeBloatMM) when building the
	// per-cell prism, so surface lying exactly on the vertical prism
	// wall isn't dropped by the Manifold intersection (which would leave
	// pinhole gaps). It's a floating-point margin only — the footprint is
	// the XY projection of the surface, so there is no surface beyond the
	// boundary to reach for. debugsvg.go renders OuterEdgeOpen edges in
	// red so a layer debug view shows the open boundary at a glance.
	//
	// nil for cells from the legacy PartitionSlab path that hasn't
	// been tagged; consumers MUST treat nil as "every edge is inner"
	// to preserve the strict-clipping behaviour those callers expect.
	OuterEdgeOpen []bool
}

// Slab is one Z-stratum of the partitioned model. ZBot < ZTop. Cells
// tile (most of) the slab's XY footprint; rasterization-based small-
// cell merge happens downstream of this package.
type Slab struct {
	// Index is the slab's index within the model's slab list, 0-based.
	Index int
	// HalfIdx tags which split half this slab belongs to (0 or 1). It
	// is 0 for the unsplit pipeline and for half 0; the Clip stage
	// groups slabs by HalfIdx so each half is clipped against its own
	// (bed-space) geometry. See docs/split-cellslicer.md.
	HalfIdx byte
	// ZBot, ZTop bound the slab in Z (mm).
	ZBot, ZTop float32
	// BotLayer / TopLayer are the slicer's per-Z contour layers at
	// ZBot and ZTop. Retained so downstream code can look up source
	// triangles for color sampling without re-slicing.
	BotLayer *Layer
	TopLayer *Layer
	// Footprint is the Clipper union of bot + top loops — the full solid
	// cross-section. Cells lie inside it, but do NOT (and should not) tile
	// all of it: the cellslicer is surface-only.
	Footprint *Footprint
	// CoverTarget is the surface shell the cells are actually meant to
	// tile: the lateral band (walls) ∪ innerCap (cap surfaces), as
	// computed by PartitionSlabAnalytic. It excludes the hidden interior
	// volume, so it is the correct reference for a coverage-gap check
	// (Footprint over-counts the interior as "uncovered"). May be nil for
	// slabs built by the PartitionSlab/PartitionModel helper path, which
	// has no neighbour context; callers should fall back to Footprint.
	CoverTarget *Footprint
	// Cells is the slab's cell list. Order is ring-cells first
	// (loop-by-loop), then hex cells.
	Cells []Cell
}
