// Package cellslicer partitions a sliced model into per-slab cells:
// small 2D polygons that tile each slab's footprint. Cells are the
// unit of color sampling and dithering in the cellslicer pipeline;
// the original mesh is later intersected (via Manifold's 3D boolean
// in clip_manifold.go) against each cell's prism so triangle fragments
// inherit the enclosing cell's color.
//
// The package owns Z-plane slicing (SliceMesh + Loop + Point2), slab
// partition, cell polygon generation, adjacency, sampling, and the
// per-cell Manifold Clip stage.
package cellslicer

// CellKind distinguishes ring cells (along the slab's boundary) from
// hex cells (filling the slab's interior).
type CellKind uint8

const (
	// KindRing is a cell generated by walking the outer footprint at
	// cellSize arc spacing; its outer edge is a chord of the
	// footprint boundary and it extends inward.
	KindRing CellKind = iota
	// KindHex is a (regular or boundary-clipped) hexagon tessellating
	// the inward-offset footprint.
	KindHex
)

// Cell is a single XY polygon at a slab. The polygon is the result
// of Clipper-clipping a raw ring trapezoid or hex against the slab's
// footprint, so it lies entirely inside the footprint and its edges
// may not be straight (each clipped polygon can have more vertices
// than the original ring/hex).
type Cell struct {
	// Outer is the cell's outer boundary, CCW, no closing duplicate.
	Outer []Point2
	Kind  CellKind
	// Pixels is the cell's pixel-count in the partition raster
	// (pxSize = cellSize/4 by default). Useful for diagnosing
	// missing-geometry dropouts. Zero when the cell was not built
	// from a raster (e.g. legacy PartitionSlab path).
	Pixels int
	// OuterEdgeOpen, when non-nil, has length len(Outer) and marks
	// whether each cell-Outer edge lies on the slab partition's outer
	// boundary — i.e. no other cell in the slab owns its reverse
	// half-edge AND the half-space immediately outside the edge falls
	// outside the slab footprint.
	//
	// ClipMeshToCellsManifold treats "outer" edges as open: it bloats
	// them outward when building the per-cell prism so source-mesh
	// fragments whose vertices nudge slightly outside the slab
	// footprint (typical of alpha-wrap discretisation on near-vertical
	// walls) still land in this cell rather than being silently
	// dropped. debugsvg.go renders OuterEdgeOpen edges in red so a
	// layer debug view shows the open boundary at a glance.
	//
	// nil for cells from the legacy PartitionSlab path that hasn't
	// been tagged; consumers MUST treat nil as "every edge is inner"
	// to preserve the strict-clipping behaviour those callers expect.
	OuterEdgeOpen []bool
}

// Slab is one Z-stratum of the partitioned model. ZBot < ZTop. Cells
// tile (most of) the slab's XY footprint; rasterization-based small-
// cell merge happens downstream of this package.
type Slab struct {
	// Index is the slab's index within the model's slab list, 0-based.
	Index int
	// ZBot, ZTop bound the slab in Z (mm).
	ZBot, ZTop float32
	// BotLayer / TopLayer are the slicer's per-Z contour layers at
	// ZBot and ZTop. Retained so downstream code can look up source
	// triangles for color sampling without re-slicing.
	BotLayer *Layer
	TopLayer *Layer
	// Footprint is the Clipper union of bot + top loops. Cells lie
	// inside it.
	Footprint *Footprint
	// Cells is the slab's cell list. Order is ring-cells first
	// (loop-by-loop), then hex cells.
	Cells []Cell
}
