// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {pipeline} from '../models';

export function CreateCollection(arg1:string):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function GetCollectionColors(arg1:string):Promise<Array<main.ColorEntry>>;

export function ImportCollection():Promise<string>;

export function IsBusy():Promise<boolean>;

export function ListCollections():Promise<Array<main.CollectionInfo>>;

export function LogMessage(arg1:string,arg2:string):Promise<void>;

export function ProcessPipeline(arg1:pipeline.Options):Promise<number>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function ResolveColor(arg1:string):Promise<main.ColorEntry>;

export function SaveCollectionColors(arg1:string,arg2:Array<main.ColorEntry>):Promise<void>;

export function SaveFile():Promise<string>;

export function SelectInputFile():Promise<string>;

export function Version():Promise<string>;
