// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function GetCollectionColors(arg1) {
  return window['go']['main']['App']['GetCollectionColors'](arg1);
}

export function ImportCollection() {
  return window['go']['main']['App']['ImportCollection']();
}

export function IsBusy() {
  return window['go']['main']['App']['IsBusy']();
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function LoadModelPreview(arg1) {
  return window['go']['main']['App']['LoadModelPreview'](arg1);
}

export function LogMessage(arg1, arg2) {
  return window['go']['main']['App']['LogMessage'](arg1, arg2);
}

export function ProcessPipeline(arg1) {
  return window['go']['main']['App']['ProcessPipeline'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function SaveFile() {
  return window['go']['main']['App']['SaveFile']();
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectInventoryFile() {
  return window['go']['main']['App']['SelectInventoryFile']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
