// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function DefaultSettingsPath(arg1) {
  return window['go']['main']['App']['DefaultSettingsPath'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function EnumerateObjects(arg1) {
  return window['go']['main']['App']['EnumerateObjects'](arg1);
}

export function Export3MF() {
  return window['go']['main']['App']['Export3MF']();
}

export function GetCollectionColors(arg1) {
  return window['go']['main']['App']['GetCollectionColors'](arg1);
}

export function ImportCollection() {
  return window['go']['main']['App']['ImportCollection']();
}

export function IsBusy() {
  return window['go']['main']['App']['IsBusy']();
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListPrinters() {
  return window['go']['main']['App']['ListPrinters']();
}

export function LoadSettingsFile(arg1) {
  return window['go']['main']['App']['LoadSettingsFile'](arg1);
}

export function LogMessage(arg1, arg2) {
  return window['go']['main']['App']['LogMessage'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenMaterialXFile() {
  return window['go']['main']['App']['OpenMaterialXFile']();
}

export function OpenStickerImage() {
  return window['go']['main']['App']['OpenStickerImage']();
}

export function ProcessPipeline(arg1) {
  return window['go']['main']['App']['ProcessPipeline'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadStickerThumbnail(arg1) {
  return window['go']['main']['App']['ReadStickerThumbnail'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function ResolveColor(arg1) {
  return window['go']['main']['App']['ResolveColor'](arg1);
}

export function SaveCollectionColors(arg1, arg2) {
  return window['go']['main']['App']['SaveCollectionColors'](arg1, arg2);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SaveSettingsDialog(arg1) {
  return window['go']['main']['App']['SaveSettingsDialog'](arg1);
}

export function SplitPreview(arg1) {
  return window['go']['main']['App']['SplitPreview'](arg1);
}

export function ValidateMaterialX(arg1) {
  return window['go']['main']['App']['ValidateMaterialX'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
