// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';

export function LoadModelPreview(arg1:string):Promise<pipeline.MeshData>;

export function LogMessage(arg1:string,arg2:string):Promise<void>;

export function RunPipeline(arg1:pipeline.Options):Promise<pipeline.Result>;

export function SelectInputFile():Promise<string>;

export function SelectOutputFile():Promise<string>;

export function Version():Promise<string>;
