// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pipeline} from '../models';

export function IsBusy():Promise<boolean>;

export function LoadModelPreview(arg1:string):Promise<void>;

export function LogMessage(arg1:string,arg2:string):Promise<void>;

export function ProcessPipeline(arg1:pipeline.Options):Promise<number>;

export function SaveFile():Promise<string>;

export function SelectInputFile():Promise<string>;

export function SelectInventoryFile():Promise<string>;

export function Version():Promise<string>;
